eshop/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove')
]

eshop/coupons/urls.py
from django.conf.urls import url
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'coupons'
urlpatterns = [
    url(_(r'^apply/$'), views.coupon_apply, name='apply'),
]

eshop/eshop/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns =  i18n_patterns (
    path('admin/', admin.site.urls),
    url(_(r'^cart/'), include('cart.urls', namespace='cart')),
    url(_(r'^orders/'), include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(_(r'^payment/'), include('payment.urls', namespace='payment')),
    url(_(r'^coupons/'), include('coupons.urls', namespace='coupons')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^', include('shop.urls', namespace='shop'))
    )


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/orders/urls.py
from django.conf.urls import url
from . import views
from django.utils.translation import gettext_lazy as _


app_name = 'orders'
urlpatterns = [
    url(_(r'^create/$'), views.order_create, name='order_create'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.admin_order_pdf, name='admin_order_pdf'),
]

eshop/shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'
urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

eshop/cart/models.py
from django.db import models

# Create your models here.

eshop/shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class SizeShoes(models.Model):
    name = models.CharField(max_length=50)
    size = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class SizeShirt(models.Model):
    name = models.CharField(max_length=50)
    size = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class SizePants(models.Model):
    name = models.CharField(max_length=50)
    size = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    size_shoes = models.ManyToManyField(SizeShoes, blank=True)
    size_shirt = models.ManyToManyField(SizeShirt, blank=True)
    size_pants = models.ManyToManyField(SizePants, blank=True)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

eshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from coupons.forms import CouponApplyForm
from .cart import Cart
from .form import CartAddProductForm
from shop.models import Product
from shop.recommender import Recommender

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True
                                                                   })
    coupon_apply_form = CouponApplyForm()

    r = Recommender()
    cart_products = [item['product'] for item in cart]
    r.products_bought([item['product'] for item in cart])
    recommended_products = r.suggest_products_for(cart_products,max_results=4)

    return render(request, 'cart/detail.html', {'cart': cart,
                                                'coupon_apply_form': coupon_apply_form,
                                                'recommended_products': recommended_products})

eshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.form import CartAddProductForm
from .recommender import Recommender


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True).order_by('-pk')
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products
                                                      })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)

    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'recommended_products': recommended_products})

eshop/shop/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
{% trans 'Shopping cart' %}
{% endblock %}

{%  block content %}
<h1> {% trans 'Shopping cart' %}</h1>
<table class='cart'>
    <thread>
        <tr>
            <th>{% trans 'Image' %}</th>
            <th>{% trans 'Product' %}</th>
            <th>{% trans 'Quantity' %}</th>
            <th>{% trans 'Delete' %}</th>
            <th>{% trans 'Price per item' %}</th>
            <th>{% trans 'Total Price' %}</th>
        </tr>
    </thread>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/No_image_available.svg' %}{% endif  %}">
            </a>
        </td>
        <td>{{ product.name }}</td>
        <td>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="{% trans 'Update' %}">
                {% csrf_token %}
            </form>
        </td>
        <td><a href="{% url 'cart:cart_remove' product.id %}">{% trans 'Delete' %}</a></td>
        <td class="num">{{ item.price }} €</td>
        <td class="num">{{ item.total_price }} €</td>
    </tr>
    {% endwith %}
    {% endfor %}
    {% if cart.coupon %}
    <tr class="subtotal">
        <td>{% trans 'Subtotal' %}</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }}</td>
    </tr>
    <tr>
        <td>
            {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
            "{{ code }}" ({{ discount }}% off)
            {% endblocktrans %}
        </td>
        <td colspan="4"></td>
        <td class="num neg">
            - {{ cart.get_discount|floatformat:"2" }}
        </td>
    </tr>
    {% endif %}
    <tr class="total">
        <td>{% trans 'Total' %}</td>
        <td colspan="4"></td>
        <td class="num">
            ${{ cart.get_total_price_after_discount|floatformat:"2" }}
        </td>
    </tbody>
</table>

{% if recommended_products %}
<div class="recommendations">
    <h3>{% trans "People who bought this also bought" %}</h3>
    {% for p in recommended_products %}
        <div class="item">
            <a href="{{ p.get_absolute_url }}">
                <img src="{% if p.image %}{{ p.image.url }}{% else %}
                {% static "img/no_image.png" %}{% endif %}">
            </a>
            <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
        </div>
    {% endfor %}
</div>
{% endif %}
<p>{% trans 'Apply a coupon' %}:</p>
<form action="{% url 'coupons:apply' %}" method="post">
{{ coupon_apply_form }}
<input type="submit" value="{% trans 'Apply' %}">
{% csrf_token %}
</form>

<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">{% trans 'Continue shopping' %}</a>
    <a href="{%  url 'orders:order_create' %}" class="button">{% trans 'Go to checkout' %}</a>
</p>


{% endblock %}